name: Build (Meson) on ino_dev

on:
  push:
    branches:
      - ino_dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build gcc libglib2.0-dev libssl-dev libperl-dev libncurses5-dev pkg-config

      - name: Show files for debug
        run: ls -l

      - name: Configure with Meson
        run: meson Build

      - name: Build with Ninja
        run: ninja -C Build

      - name: Upload binary (optional)
        uses: actions/upload-artifact@v4
        with:
          name: irssi-binary
          path: Build/src/irssi
