name: Build on ino_dev

on:
  push:
    branches:
      - ino_dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y automake libtool pkg-config gcc libglib2.0-dev libssl-dev libncurses5-dev

      - name: Show directory contents (diagnostic)
        run: ls -l

      - name: Configure (if exists)
        run: |
          if [ -f ./configure ]; then
            chmod +x ./configure
            ./configure
          else
            echo "Brak pliku configure – przerwano build."
            exit 1
          fi

      - name: Build irssi
        run: make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: irssi-binary
          path: src/irssi
